### ISSUE TITLE
'SourceCodeRenderer' object has no attribute 'render_Constant'

### ISSUE THREAD

**Issue by virophagesp** [boppreh/replace_me#2]
i tried running pycc-transform --source SOURCE.py  --destination DESTINATION.py --constants
but i got this error
Traceback (most recent call last):
  File "/home/corre/.local/bin/pycc-transform", line 8, in <module>
    sys.exit(main())
  File "/home/corre/.local/lib/python3.8/site-packages/pycc/cli/transform.py", line 29, in main
    bytecode = source_compiler(
  File "/home/corre/.local/lib/python3.8/site-packages/pycc/asttools/compiler.py", line 103, in __call__
    return SourceCodeRenderer.render(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 41, in render
    renderer.visit(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 71, in visit
    self._render(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 48, in _render
    return render_method(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 440, in render_Module
    self._render_statements(node.body)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 75, in _render_statements
    self._render(stmt)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 48, in _render
    return render_method(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 293, in render_Expr
    self.emit(self._render(node.value))
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 48, in _render
    return render_method(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 176, in render_Call
    acc += self._render(node.args)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 48, in _render
    return render_method(node)
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 413, in render_list
    return separator.join([self._render(elt) for elt in elts])
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 413, in <listcomp>
    return separator.join([self._render(elt) for elt in elts])
  File "/home/corre/.local/lib/python3.8/site-packages/astkit/render.py", line 47, in _render
    render_method = getattr(self, 'render_%s' % node.__class__.__name__)
AttributeError: 'SourceCodeRenderer' object has no attribute 'render_Constant'

**Comment by virophagesp** [comment]
wrong page

**Comment by virophagesp** [comment]
wrong repository
